services:
  frontend:
    build: .
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}

      NEXT_PUBLIC_TELEGRAM_BOT_TOKEN: ${NEXT_PUBLIC_TELEGRAM_BOT_TOKEN}
      NEXT_PUBLIC_TELEGRAM_CHAT_ID: ${NEXT_PUBLIC_TELEGRAM_CHAT_ID}

      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      NEXT_PUBLIC_RECAPTCHA_SECRET_KEY: ${NEXT_PUBLIC_RECAPTCHA_SECRET_KEY}
    ports:
      - '3000:3000'
    extra_hosts:
      - "host.docker.internal:host-gateway" # "maxximum.by:host-gateway"
      - "k-r.by:172.20.0.1"
  
  proxy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # For HTTP/3 support
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    name: public_net
    external: true
